### ISSUE TITLE
Can not find openssl

### ISSUE THREAD

**Issue by oh2gqc** [TotalTechGeek/pictoprime#1]
pictoprime throws error:
if (!await commandExists('openssl').then(() => true).catch(() => false)) throw new Error('You must have openssl in your path for this program to work.')

However openssl **is** in my path:
$ which openssl
/usr/bin/openssl

$ echo $PATH
/home/karza/julia-1.7.1/bin:/home/karza/.cargo/bin:/home/karza/.local/bin:/home/karza/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:**/usr/bin**:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Running on XUbuntu 18.04.6 LTS

**Comment by tobyink** [comment]
I encountered this too.

What version of node.js do you have installed? Using `await` outside `async` functions (which this project does a few times) requires node.js 14.8.0 or above.

```
node -v
```

**Comment by oh2gqc** [comment]
Hi, 

Seems that I had a very old version on node ( 12. something )
Updated node and now pictoprime works.
Thanks you for your help tobyink!
