### ISSUE TITLE
openssl not installed even though it is

### ISSUE THREAD

**Issue by viprfocus** [TotalTechGeek/pictoprime#10]
pictoprime error:
Error: You must have openssl in your path for this program to work.
    at main (file:///C:/Users/Pepe/AppData/Roaming/npm/node_modules/pictoprime/index.js:36:84)
  my node.js version is v18.1.0  so thats not the issue

**Comment by TotalTechGeek** [comment]
Hi,

Could you type 

`where openssl`

And paste the result?

Have you installed OpenSSL & added it to your path?

**Comment by TotalTechGeek** [comment]
Closing due to stale issue
