### ISSUE TITLE
getting install errors with all deps.

### ISSUE THREAD

**Issue by jmerc77** [TotalTechGeek/pictoprime#15]
[pictoprime_install_err.txt](https://github.com/TotalTechGeek/pictoprime/files/8790330/pictoprime_install_err.txt)

on win 10 pro x64. using x64 versions of node and the rest. have not tried downgrade to x32.

as far as I know all deps are installed correctly. not sure about openssl though. I installed via >choco install openssl
which seemed to work fine.

**Comment by TotalTechGeek** [comment]
Hm, from your logs, it doesn't seem to think GraphicsMagick is present in your path, 

> 1046 error Installing lwip. If this fails, just install GraphicsMagick (http://www.graphicsmagick.org/).
1046 error It seems like lwip failed to be intalled. Please check the errors.

Could you try typing `where gm` and see what it produces?

Thanks!

**Comment by jmerc77** [comment]
INFO: Could not find files for the given pattern(s).
about to check PATH env var.

**Comment by jmerc77** [comment]
c:\program files\graphicsmagick-1.3.36-q8 in system PATH. maybe reboot??? ran into that before. about to reboot now.

**Comment by jmerc77** [comment]
that fixed it. maybe you could mention requiring a reboot after all deps so others will know.
