### ISSUE TITLE
Error with pictoprime -i: Stream yields empty buffer

### ISSUE THREAD

**Issue by lucafossen** [TotalTechGeek/pictoprime#4]
Getting this error in powershell from running `pictoprime -i shapes.png`
![image](https://user-images.githubusercontent.com/62906154/166073526-3385ada5-af95-4834-8b68-7cb918698f70.png)

Image i tried to use:
<img width="250" alt="shapes" src="https://user-images.githubusercontent.com/62906154/166073078-ba86841b-ebf0-4813-ab18-da83d6f523b9.png">
Is this an issue on my side? haven't been able to make this work on any image. Am happy to provide any additional info.
Cheers

**Comment by TotalTechGeek** [comment]
Hi Luca, it appears that the issue might have something to do with [GraphicsMagick / ImageMagick](https://www.npmjs.com/package/gm).

Are the binaries for GraphicsMagick in your path? 

You can test by running `where gm`

**Comment by lucafossen** [comment]
![image](https://user-images.githubusercontent.com/62906154/166074409-64e30f65-5775-4e10-a246-718d7cae9713.png)
`where gm` returns nothing
it appears there is a cmdlet called "gm"...?
![image](https://user-images.githubusercontent.com/62906154/166074516-d3d96e31-7fd4-419b-b844-0c98cd7f7d6b.png)

**Comment by TotalTechGeek** [comment]
Interesting. 

Could you try switching to Command Prompt & executing the same command? Either by typing `cmd` into PowerShell, or by just opening a vanilla command prompt window?

**Comment by TotalTechGeek** [comment]
It appears there might be a conflict in the gm module with PowerShell, according to this GitHub issue:
https://github.com/aheckmann/gm/issues/241

**Comment by lucafossen** [comment]
I managed to add gm to path and am getting a path when doing `where gm`, but I'm still getting the same error in cmd.
![image](https://user-images.githubusercontent.com/62906154/166075533-6361f405-bc21-4ba3-af4c-e1f76a29aa0b.png)

![image](https://user-images.githubusercontent.com/62906154/166075475-576e9ef3-69b8-4bd1-a550-72fbd7461043.png)

**Comment by lucafossen** [comment]
I got it working with WSL!
![image](https://user-images.githubusercontent.com/62906154/166082941-8ae2d78d-5cdd-4919-b8af-d1f642f2eff5.png)
something weird with the GraphicsMagick Windows installation, it seems..

**Comment by HansAnonymous** [comment]
Hello! I've also encountered this error and to not just say, "me too!" and leave, I come with a temporary solution!

It appears that GraphicsMagick just fails to run on current installations as [seen here](https://sourceforge.net/p/graphicsmagick/bugs/656/)

The solution also listed in the link above is to install Visual Studio 2008 package found [here](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2008-vc-90-sp1-no-longer-supported). Make sure it's VS2008!

Less than ideal, but GM works, allowing PictoPrime to run.

**Comment by TotalTechGeek** [comment]
Thank you @HansAnonymous, I'll try to look into a more long term solution, but with your solution I'm going to close the issue & pin it in case anyone else comes across this.

**Comment by lucafossen** [comment]
> It appears that GraphicsMagick just fails to run on current installations as [seen here](https://sourceforge.net/p/graphicsmagick/bugs/656/)
> 
> The solution also listed in the link above is to install Visual Studio 2008 package found [here](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2008-vc-90-sp1-no-longer-supported). Make sure it's VS2008!

Thank you! It is now working natively for me as well.
![image](https://user-images.githubusercontent.com/62906154/166083371-275348fd-b9e2-4057-8ca4-892fc9213927.png)
