### ISSUE TITLE
ERR_UNHANDLED_REJECTION

### ISSUE THREAD

**Issue by galaflux** [TotalTechGeek/pictoprime#6]
Hey so, I didn't wanna drop a report until I really hit a wall. I'm not terribly tech savvy, so it's totally possible I missed some kinda step in here, but I figured I'd ask rather than keep banging my head against a wall. I've been trying to run this program on my laptop for about two days on and off (ever since seeing the StandUpMaths video that talks about it) and I keep running into the same error. Install GraphicsMagick, node, and openssl, but it still seems to come up and I was wondering if anyone knew how to fix it. I run it in cmd and I get the same error over and over. I'll attach the screenshot with the pic I'm trying to test this on. Please let me know when you can, thanks!
![image](https://user-images.githubusercontent.com/24710199/166161854-efab03ec-27e4-481d-8c68-9246b70d1b67.png)
![pi](https://user-images.githubusercontent.com/24710199/166161857-738c7f83-c114-4239-9a67-1ef3c4999ef2.png)

**Comment by TotalTechGeek** [comment]
Hi, in the immediate term, please accept this prime:
```
777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777772994440000000000000000000009777777777777777777777777777777777724888888888889888888888888888477777777777777777777777777777777770099222208022222220888922222227777777777777777777777777777777774977777770847777777088877777777777777777777777777777777777777772277777777889777777288807777777777777777777777777777777777777777777777777288977777728880777777777777777777777777777777777777777777777777748827777779888977777777777777777777777777777777777777777777777728887777777488897777777777777777777777777777777777777777777777774880777777708882777777777777777777777777777777777777777777777779888477777778888277777777777777777777777777777777777777777777774888897777772888827777777277777777777777777777777777777777777720888882777777288884777777997777777777777777777777777777777777798888884777777728888809229007777777777777777777717777777777777770888880277777777988888888847777777777777777777777777777777777777240009777777777772940000927777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777
```

I pushed a new version that'll attempt to log the error differently, could you try running it & seeing if it produces anything different?

**Comment by galaflux** [comment]
Hello! I am sorry for the late response, as I had a few errands to run, but I gave it another go with the new version, and I got a different output, as you said. The image follows. Also, thank you for the prime, it is lovely.
![image](https://user-images.githubusercontent.com/24710199/166169073-3ee6bd4b-5914-4b41-913f-ae5721a97611.png)

**Comment by TotalTechGeek** [comment]
Hi, it appears it may be this issue: https://github.com/TotalTechGeek/pictoprime/issues/4#issuecomment-1113873310

If following the steps in the comment works, I will try to update Readme to include those steps for Windows users.

**Comment by galaflux** [comment]
![image](https://user-images.githubusercontent.com/24710199/166173565-af1186fb-ee9c-4841-b596-45963029d9f9.png)
I am pleased to announce that it worked!!! Thank you so much for your help and please, have a good day!
