### ISSUE TITLE
Is this supposed to only give the prime number or also create a picture of it?

### ISSUE THREAD

**Issue by Eevee97** [TotalTechGeek/pictoprime#7]
After some trying and problem solving I managed to get the code working to give the resulting long prime number. I was wondering if it was also supposed to give a resulting image with the numbers or is it something I should do myself? I'm not an expert so I wasn't sure. I only get the prime number.

I was of course able to make the image myself, was just wondering if there was some problem still. Very cool idea and program in any case!

I'm on Windows 11 and ran the program on the command prompt in case it matters. I have so little experience with these things that I needed to install every dependency first.

**Comment by TotalTechGeek** [comment]
Right now, it just outputs the number, so users can use it in whatever medium they prefer 🙂

**Comment by Eevee97** [comment]
Okay, thank you! A small suggestion might be to mention how many digits in a row there are (at least I didn't notice it). I just counted from the example and it worked fine, but when both edges have a lot of eights, it's not obvious where the next row begins. Of course it's not that hard to count the first row (I think it was 64 digits/row).
