### ISSUE TITLE
changing width/contrast

### ISSUE THREAD

**Issue by hamm3rhand** [TotalTechGeek/pictoprime#9]
what is the full command to change width and contrast? i can consistently get a 32 width prime, but I always get errors when trying to change the width. 

for example, when I try "pictoprime --width = 64" then i get: Error: Either a number or an image must be specified.

 i've tried pretty much every variation i can think of for denoting a number and it usually gives that error. 

pictoprime --width       (nothing afterwards) this will give error: option '--width <width>' argument missing

So i tried "pictoprime --width <64>"  but that gave the following message 
At line:1 char:20
+ pictoprime --width <64>
+                    ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

I've also tried editing the image javascript file directly but that doesn't seem to change anything. any thoughts? i've tried updating, uninstall and reinstall, nothing seems to work. The pictures look good but would like to get them a bit bigger. 

very cool program by the way!

**Comment by TotalTechGeek** [comment]
Hi,

Could you try `pictoprime --width 64`? 

Thanks!

**Comment by hamm3rhand** [comment]
that gives the error as follows (username removed) 

Error: Either a number or an image must be specified.
    at main (file:///C:/Users/****/AppData/Roaming/npm/node_modules/pictoprime/index.js:38:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by TotalTechGeek** [comment]
You'll need to specify an image (with `-i imagename`) or a long number (with `-n 77777777777777777777777777777777777777777777777777777777777777777777777777777`)

**Comment by hamm3rhand** [comment]
oh, i see, you do both operations in the same command. thanks!
